spring:
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: jdbc:mysql://db:3307/myhouse24
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 971647332c46fff334ce
            clientSecret: b50eb4e1c6c2c273c796ef55fc39325f0da824a9
  mail:
    host: smtp.gmail.com
    port: 587
    username: kripword@gmail.com
    password: kriptwordgmail1com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
cloud:
  aws:
    credentials:
      access-key: AKIAZ6GXNB7ZA2A7WE53
      secret-key: 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
    region:
      static: eu-north-1
    stack:
      auto: false
application:
  bucket:
    name: awss3bucketforavadatest
server:
  servlet:
    context-path: /myHouse24DA