#logging:
#  level:
#    org.springframework.security: DEBUG
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/house24
    username: root
    password: ${DATABASE_PASSWORD}
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${GITHUB_CLIENT_ID}
            clientSecret: ${GITHUB_CLIENT_SECRET}
  mail:
    host: smtp.gmail.com
    port: 587
    username: freeideamonthly1@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com