spring:
  messages:
    basename: i18n/messages
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 15MB
      max-request-size: 20MB
  datasource:
    url: jdbc:mysql://mysql-container24DA:3306/house24
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: freeideamonthly1@gmail.com
    password: kxmtyqlqbqcjaoyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
  mvc:
    static-path-pattern: /resources/**
  web:
    resources:
      static-locations: classpath:/static/
  rabbitmq:
    host: rabbitmqda
    port: 15672
    username: guest
    password: guest
  devtools:
    restart:
      enabled: true
server:
  servlet:
    context-path: /myHouse24DA
  port: 414
