spring:
  messages:
    basename: i18n/messages
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/house24
    username: root
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: freeideamonthly1@gmail.com
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
upload:
  path: C:\Users\NikkiLA\Desktop\SpringProject\images