name: CI/CD containerization

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package
      - name: Build Docker image
        run: |
          docker build -t myhouse24-admin:latest .
          docker-compose down
          docker-compose up -d