name: CI/CD containerization

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t myhouse24:latest .

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull myhouse24:latest

      - name: Stop and Remove Existing Containers
        run: docker-compose down

      - name: Start Containers
        run: docker-compose up -d