name: Docker Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker images
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: "./docker-compose.yml"

      - name: Tag Docker images
        run: |
          docker tag myhouse24-admin:latest ${{ secrets.DOCKERHUB_USERNAME }}/myhouse24-admin:latest
          docker tag myhouse24-user:latest ${{ secrets.DOCKERHUB_USERNAME }}/myhouse24-user:latest

      - name: Push Docker images to Docker Hub
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myhouse24-admin:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/myhouse24-user:latest
